name: arcane_jaspr_win95
description: Windows 95 renderer package for Arcane Jaspr.
version: 5.0.1
homepage: https://arcanearts.github.io/arcane_jaspr/
documentation: https://arcanearts.github.io/arcane_jaspr/
repository: https://github.com/ArcaneArts/arcane_jaspr

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  arcane_jaspr: ^5.0.0
  jaspr: '>=0.23.1 <1.0.0'

dev_dependencies:
  lints: ^6.1.0
